# Generated by Django 3.2.9 on 2021-12-02 17:03

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPRN',
            fields=[
                ('uprn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('postcode', models.CharField(db_index=True, max_length=7)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('addressbase', models.JSONField()),
            ],
            options={
                'ordering': ('uprn',),
            },
        ),
        migrations.AddIndex(
            model_name='uprn',
            index=django.contrib.postgres.indexes.GinIndex(fields=['addressbase'], name='mapit_labou_address_655eac_gin'),
        ),
    ]
