# Generated by Django 3.2.10 on 2021-12-07 14:11

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='UPRN',
            fields=[
                ('uprn', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=7)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('addressbase', models.JSONField()),
                ('single_line_address', models.TextField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('uprn',),
            },
        ),
        migrations.AddIndex(
            model_name='uprn',
            index=django.contrib.postgres.indexes.GinIndex(fields=['addressbase'], name='mapit_labou_address_655eac_gin'),
        ),
        migrations.AddIndex(
            model_name='uprn',
            index=django.contrib.postgres.indexes.GinIndex(fields=['single_line_address'], name='mapit_labour_sl_address_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
