# Generated by Django 3.2.9 on 2021-12-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapit_labour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uprn",
            name="single_line_address",
            field=models.TextField(db_index=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uprn",
            name="postcode",
            field=models.CharField(max_length=7),
        ),
    ]
