# Generated by Django 3.2.10 on 2021-12-08 21:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_labour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprn',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=27700),
        ),
    ]
