# Generated by Django 3.2.9 on 2021-12-03 23:00

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('mapit_labour', '0002_auto_20211203_2038'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name='uprn',
            name='single_line_address',
            field=models.TextField(db_index=True, editable=False),
        ),
        migrations.AddIndex(
            model_name='uprn',
            index=django.contrib.postgres.indexes.GinIndex(fields=['single_line_address'], name='mapit_labour_sl_address_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
