# Generated by Django 3.2.12 on 2022-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_labour', '0005_csvimporttaskprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimporttaskprogress',
            name='task_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
